# This is a basic workflow to help you get started with Actions

name: Run Test Configuration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: echo "Trigger event.. ${{github.event_name}}. Runner OS.. ${{ runner.os }}."
      - name: Eggplant Runner
      - uses: keysight-eggplant/eggplant-github-action@v1.0.4
      
        with:
        # The URL of Eggplant DAI server, e.g. http://localhost:8000
          serverURL: http://localhost:8000/
    # The ID of the Eggplant DAI test configuration that you want to run, e.g. 09c48b7d-fc5b-481d-af80-fcffad5d9587
          testConfigID: 2b43fd4b-c576-4f6e-9112-7b56131459aa
    # The client ID to use to authenticate with the Eggplant DAI server  [default: client:dai:agent:integration]
          clientID: client:dai:agent:integration
    # The client secret to use to authenticate with the Eggplant DAI server  [env var: DAI_CLIENT_SECRET; required]
          clientSecret: 249daf3f-2a7a-4072-9b63-15f393a4ba4a
      

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
