# This is a basic workflow to help you get started with Actions

name: Run Test Configuration

on:
  push: 
   branches:
     - main
  pull_request:
    branches:
     - main
  
jobs:
  Run_Test_Configuration:
    runs-on: self-hosted
    name: Run Test Configuration
    steps:
      - run: echo "Trigger event.. ${{ github.eventname }}. Runner OS.. ${{ runner.os }}."
      - name: Eggplant Runner
        uses: keysight-eggplant/eggplant-github-action@v1.0.4
        with:
          serverURL: http://localhost:8000
          testConfigID: 2b43fd4b-c576-4f6e-9112-7b56131459aa
          clientID: client:dai:agent:integration
          clientSecret: 249daf3f-2a7a-4072-9b63-15f393a4ba4a
      
